name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  lint:
    name: Lint Check
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew lintDebug --stacktrace
